import type { DivisionCode, Issue } from "./issue-model";

/**
 * Twenty demo records. Every value is invented placeholder text — no real issue,
 * person or figure from the source application appears here.
 */

const LOREM_1 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`;

const LOREM_2 = `Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.

Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.`;

const LOREM_3 = `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.

Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat.`;

const LOREM_4 = `Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.

Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`;

const BODIES = [LOREM_1, LOREM_2, LOREM_3, LOREM_4];

function ago(days: number): string {
  return new Date(Date.now() - days * 86_400_000).toISOString().slice(0, 10);
}

type Row = {
  title: string;
  country: string;
  lead: string;
  team: string[];
  divisions: DivisionCode[];
  leadDivision: DivisionCode;
  businessArea: Issue["businessArea"];
  actionability: Issue["actionability"];
  funnelStage: Issue["funnelStage"];
  uniqueness: Issue["uniqueness"];
  qualitativeImpact: Issue["qualitativeImpact"];
  driver: Issue["financialImpactDriver"];
  worst: number | null;
  best: number | null;
  /** Days since the last update, so a few records read as stale. */
  age: number;
  /** Closed records also carry the value recorded at closure. */
  closureValue?: number;
  /** Deliberately incomplete records, to show the amber tab markers. */
  sparse?: boolean;
  attachments?: number;
};

const ROWS: Row[] = [
  {
    title: "Lorem ipsum reimbursement framework",
    country: "FR",
    lead: "Ada Lorem",
    team: ["Marius Ipsum", "Nora Dolor"],
    divisions: ["PH", "CO"],
    leadDivision: "PH",
    businessArea: "Registration & Market Access",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Industry Issue",
    qualitativeImpact: "High",
    driver: "Price",
    worst: 12.5,
    best: 34.2,
    age: 72,
    attachments: 2,
  },
  {
    title: "Dolor sit amet import tariff review",
    country: "BR",
    lead: "Tomas Amet",
    team: ["Livia Consecte"],
    divisions: ["CS", "CH"],
    leadDivision: "CS",
    businessArea: "Trade Agreements & Tariffs",
    actionability: "Very Likely",
    funnelStage: "Crisis Management",
    uniqueness: "Bayer is Frontrunner",
    qualitativeImpact: "Very High",
    driver: "COGS",
    worst: 22,
    best: 11.3,
    age: 30,
    closureValue: 18.4,
    attachments: 1,
  },
  {
    title: "Consectetur packaging waste levy",
    country: "PL",
    lead: "Ewa Adipisci",
    team: ["Piotr Elit"],
    divisions: ["CH", "CS"],
    leadDivision: "CH",
    businessArea: "Sustainability & Environment",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Cross-Industry Issue",
    qualitativeImpact: "Medium",
    driver: "OpEx",
    worst: 9,
    best: 2,
    age: 12,
  },
  {
    title: "Tempor incididunt labelling rules",
    country: "DE",
    lead: "Klara Tempor",
    team: ["Jonas Labore", "Rita Magna"],
    divisions: ["PH"],
    leadDivision: "PH",
    businessArea: "Product Safety & Stewardship",
    actionability: "Possible",
    funnelStage: "Issue Management",
    uniqueness: "Industry Issue",
    qualitativeImpact: "Low",
    driver: "OpEx",
    worst: 3.4,
    best: 6.1,
    age: 5,
    attachments: 1,
  },
  {
    title: "Ut enim ad minim data transfer bill",
    country: "US",
    lead: "Grace Minim",
    team: ["Owen Veniam"],
    divisions: ["CO"],
    leadDivision: "CO",
    businessArea: "Compliance & Corporate Governance",
    actionability: "Very Likely",
    funnelStage: "Issue Management",
    uniqueness: "Cross-Industry Issue",
    qualitativeImpact: "High",
    driver: "Fine",
    worst: 41,
    best: 4.5,
    age: 18,
  },
  {
    title: "Quis nostrud generics substitution",
    country: "ES",
    lead: "Alba Nostrud",
    team: ["Diego Exercit"],
    divisions: ["PH"],
    leadDivision: "PH",
    businessArea: "Market Development",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Bayer Owned",
    qualitativeImpact: "High",
    driver: "Sales",
    worst: 18.2,
    best: 27.9,
    age: 44,
  },
  {
    title: "Ullamco laboris seed treatment ban",
    country: "IT",
    lead: "Sofia Ullamco",
    team: ["Marco Laboris", "Elena Nisi"],
    divisions: ["CS"],
    leadDivision: "CS",
    businessArea: "Registration & Market Access",
    actionability: "Very Likely",
    funnelStage: "Crisis Management",
    uniqueness: "Bayer is Frontrunner",
    qualitativeImpact: "Very High",
    driver: "Sales",
    worst: 55.6,
    best: 8.4,
    age: 3,
    attachments: 3,
  },
  {
    title: "Aliquip ex ea import licensing delay",
    country: "IN",
    lead: "Priya Aliquip",
    team: ["Rahul Commodo"],
    divisions: ["PH", "CH"],
    leadDivision: "CH",
    businessArea: "Registration & Market Access",
    actionability: "Possible",
    funnelStage: "Issue Management",
    uniqueness: "Industry Issue",
    qualitativeImpact: "Medium",
    driver: "COGS",
    worst: 7.8,
    best: 12.6,
    age: 91,
  },
  {
    title: "Duis aute irure advertising code",
    country: "UK",
    lead: "Helen Duis",
    team: [],
    divisions: ["CH"],
    leadDivision: "CH",
    businessArea: "Marketing, Sales & Distribution",
    actionability: "Possible",
    funnelStage: "Thought Leadership",
    uniqueness: "No Value Selected",
    qualitativeImpact: "Low",
    driver: "Sales",
    worst: 2.1,
    best: 5.3,
    age: 27,
    sparse: true,
  },
  {
    title: "Reprehenderit voluptate patent term",
    country: "CN",
    lead: "Wei Volupt",
    team: ["Lin Velit", "Chen Esse"],
    divisions: ["PH", "CO"],
    leadDivision: "PH",
    businessArea: "Legal & Intellectual Property",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Bayer Owned",
    qualitativeImpact: "Very High",
    driver: "Sales",
    worst: 63.4,
    best: 44.8,
    age: 9,
    attachments: 2,
  },
  {
    title: "Cillum dolore carbon border levy",
    country: "NL",
    lead: "Sanne Cillum",
    team: ["Bram Dolore"],
    divisions: ["CS", "CO"],
    leadDivision: "CO",
    businessArea: "Sustainability & Environment",
    actionability: "Likely",
    funnelStage: "Thought Leadership",
    uniqueness: "Cross-Industry Issue",
    qualitativeImpact: "Medium",
    driver: "CapEx",
    worst: 14.7,
    best: 9.2,
    age: 66,
  },
  {
    title: "Fugiat nulla pricing transparency act",
    country: "JP",
    lead: "Yuki Fugiat",
    team: ["Haru Nulla"],
    divisions: ["PH"],
    leadDivision: "PH",
    businessArea: "Finance, Tax & Accounting",
    actionability: "Very Likely",
    funnelStage: "Issue Management",
    uniqueness: "Industry Issue",
    qualitativeImpact: "High",
    driver: "Price",
    worst: 31.5,
    best: 6.8,
    age: 21,
    closureValue: 12.9,
  },
  {
    title: "Excepteur sint biocide reapproval",
    country: "CZ",
    lead: "Jana Excepteur",
    team: ["Petr Sint"],
    divisions: ["CS"],
    leadDivision: "CS",
    businessArea: "Registration & Market Access",
    actionability: "Possible",
    funnelStage: "Issue Management",
    uniqueness: "Bayer Owned",
    qualitativeImpact: "Medium",
    driver: "Sales",
    worst: 11.2,
    best: 19.4,
    age: 38,
  },
  {
    title: "Occaecat cupidatat retail margin cap",
    country: "MX",
    lead: "Lucia Occaecat",
    team: ["Javier Cupidat", "Rosa Proident"],
    divisions: ["CH"],
    leadDivision: "CH",
    businessArea: "Marketing, Sales & Distribution",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Industry Issue",
    qualitativeImpact: "Medium",
    driver: "Price",
    worst: 8.9,
    best: 15.1,
    age: 54,
  },
  {
    title: "Sunt in culpa clinical trial disclosure",
    country: "ZA",
    lead: "Thandi Culpa",
    team: ["Sipho Officia"],
    divisions: ["PH"],
    leadDivision: "PH",
    businessArea: "Reputation Management",
    actionability: "Possible",
    funnelStage: "Thought Leadership",
    uniqueness: "Cross-Industry Issue",
    qualitativeImpact: "Low",
    driver: "OpEx",
    worst: 1.8,
    best: 3.7,
    age: 74,
    sparse: true,
  },
  {
    title: "Deserunt mollit fertiliser subsidy reform",
    country: "AR",
    lead: "Mateo Deserunt",
    team: ["Camila Mollit"],
    divisions: ["CS"],
    leadDivision: "CS",
    businessArea: "Trade Agreements & Tariffs",
    actionability: "Very Likely",
    funnelStage: "Crisis Management",
    uniqueness: "Bayer is Frontrunner",
    qualitativeImpact: "High",
    driver: "Subsidy",
    worst: 26.3,
    best: 21.7,
    age: 15,
    attachments: 1,
  },
  {
    title: "Anim id est parallel trade restriction",
    country: "SK",
    lead: "Zuzana Anim",
    team: ["Martin Laborum"],
    divisions: ["PH", "CH"],
    leadDivision: "PH",
    businessArea: "Market Development",
    actionability: "Likely",
    funnelStage: "Issue Management",
    uniqueness: "Industry Issue",
    qualitativeImpact: "Medium",
    driver: "Sales",
    worst: 6.4,
    best: 13.8,
    age: 48,
    closureValue: 7.5,
  },
  {
    title: "Perspiciatis unde digital health decree",
    country: "IE",
    lead: "Aoife Perspic",
    team: [],
    divisions: ["PH", "CO"],
    leadDivision: "CO",
    businessArea: "Compliance & Corporate Governance",
    actionability: "Possible",
    funnelStage: "Thought Leadership",
    uniqueness: "No Value Selected",
    qualitativeImpact: "Low",
    driver: "CapEx",
    worst: null,
    best: null,
    age: 6,
    sparse: true,
  },
  {
    title: "Natus error crop protection residue limits",
    country: "TH",
    lead: "Nong Natus",
    team: ["Anan Error", "Ploy Voluptatem"],
    divisions: ["CS", "CH"],
    leadDivision: "CS",
    businessArea: "Product Safety & Stewardship",
    actionability: "Very Likely",
    funnelStage: "Crisis Management",
    uniqueness: "Bayer Owned",
    qualitativeImpact: "Very High",
    driver: "Sales",
    worst: 37.2,
    best: 16.5,
    age: 33,
    closureValue: 22.6,
    attachments: 2,
  },
  {
    title: "Accusantium doloremque global tax rule",
    country: "GL",
    lead: "Iris Accusant",
    team: ["Felix Doloremque"],
    divisions: ["CO", "PH", "CH", "CS"],
    leadDivision: "CO",
    businessArea: "Finance, Tax & Accounting",
    actionability: "Likely",
    funnelStage: "Proactive Shaping",
    uniqueness: "Cross-Industry Issue",
    qualitativeImpact: "High",
    driver: "Fine",
    worst: 48.9,
    best: 29.3,
    age: 63,
    closureValue: 31.4,
  },
];

export const DEMO_ISSUES: Partial<Issue>[] = ROWS.map((r, idx) => {
  const body = BODIES[idx % BODIES.length];
  const closed = r.closureValue !== undefined;
  const assessments = {
    CO: { businessUnit: "Not Applicable", impact: "None" as const, policyPressurePoint: false },
    PH: { businessUnit: "Not Applicable", impact: "None" as const, policyPressurePoint: false },
    CH: { businessUnit: "Not Applicable", impact: "None" as const, policyPressurePoint: false },
    CS: { businessUnit: "Not Applicable", impact: "None" as const, policyPressurePoint: false },
  };
  for (const d of r.divisions) {
    assessments[d] = {
      businessUnit: d === r.leadDivision ? "Cross-Divisional" : "Other / Several",
      impact: (d === r.leadDivision ? "High" : "Medium") as never,
      policyPressurePoint: d === r.leadDivision,
    };
  }

  return {
    id: `demo-issue-${1001 + idx}`,
    issueNo: 1001 + idx,
    title: r.title,
    country: r.country,
    lead: r.lead,
    team: r.team,
    description: body,
    divisions: r.divisions,
    leadDivision: r.leadDivision,
    businessArea: r.businessArea,
    actionability: r.actionability,
    funnelStage: r.funnelStage,
    uniqueness: r.uniqueness,
    assessments,
    qualitativeImpact: r.qualitativeImpact,
    financialImpactDriver: r.driver,
    // A sparse record keeps the scenario tab empty, so its tab marker stays amber.
    worstCaseRisk: r.sparse ? "" : BODIES[(idx + 1) % BODIES.length],
    worstCaseSalesValue: r.worst,
    worstCaseCashFlow: r.worst === null ? null : Number((r.worst * 0.8).toFixed(1)),
    bestCaseOpportunity: r.sparse ? "" : BODIES[(idx + 2) % BODIES.length],
    bestCaseSalesValue: r.best,
    bestCaseCashFlow: r.best === null ? null : Number((r.best * 0.8).toFixed(1)),
    closed,
    closureImpactType: closed ? "Value Protected" : "",
    closureDriver: closed ? r.driver : "",
    closureDate: closed ? ago(r.age) : null,
    closureDescription: closed ? body : "",
    closureSalesValue: r.closureValue ?? null,
    closureCashFlow: r.closureValue ? Number((r.closureValue * 0.78).toFixed(1)) : null,
    attachments: Array.from({ length: r.attachments ?? 0 }, (_, n) => ({
      name: `${r.title.split(" ")[0]} document ${n + 1}.docx`,
      kind: "docx" as const,
      size: `${120 + n * 47} KB`,
      addedOn: ago(r.age + n + 1),
    })),
    locked: closed,
    lastUpdate: ago(r.age),
    lastUpdateBy: r.lead,
  };
});
